### ISSUE TITLE
Coldcard v4.1.6 failed on Windows WSL Builder

### ISSUE THREAD

**Issue by brianddk** [brianddk/attestation#11]
- [x] Invited Coldcard maintainer @nvk to join discussion
- [x] Emailed [Security@coinkite.com](mailto:Security@coinkite.com)
- [ ] Attach a redacted tee'd `build.log`

https://github.com/brianddk/attestation/blob/dc7f826afaf5fa109baca4cca4539c15e94f9070/coldcard/failed/2022-10-05T1517-v4.1.6/attest.temp#L39-L44

**Comment by doc-hex** [comment]
please have a look at 4.1.8 just released today. It should reproduce perfectly.

**Comment by brianddk** [comment]
Thx @doc-hex , I verified 4.1.8 looks good

https://github.com/brianddk/attestation/blob/09cc71c/coldcard/attest/2023-06-19T1627-v4.1.8/attest.brianddk
